[settings]
# display settings
caption = "Atari Breakout"
icon = "static/icon.png"

# display resolution
cell_size = 10
num_cells_row = 100
num_cells_col = 50
padding = 10

# game settings
fps = 60

# brick sizes
brick_cells_row = 10
brick_cells_col = 2

# general settings
paddle_speed = 5
paddle_scale = 2

[colours]
background = "#000000"
paddle = "#FF9999"
single_hit_brick = "#99FF99"
double_hit_brick = "#80DFFF"
triple_hit_brick = "#FFFF99"