[settings]
# display settings
caption = "Atari Breakout"
icon = "static/icon.png"

# display resolution
cell_size = 10
num_cells_row = 100
num_cells_col = 50
padding = 10

# game settings
fps = 60

# brick sizes
brick_cells_col = 10
brick_cells_row = 2

# general settings
paddle_speed = 5

[colours]
background = "#000000"
paddle = "#FF9999"